name: Deploy to Nest

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.KEY }}" > ~/.ssh/id_ed25519
          chmod 700 ~/.ssh
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H hackclub.app >> ~/.ssh/known_hosts

      - name: Deploy to Nest
        run: |
          ssh candyisacat@hackclub.app << 'EOF'
            set -e
            cd website/website
            git stash
            git pull origin main
            git stash pop || true
            npm install
            npm run build
            systemctl --user restart starcoral
          EOF